name: Deploy Local Store
on:
  push:
    tags: 'release-local-store-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g yarn lerna
      - run: lerna bootstrap
      - run: lerna run build

      # - run: cd packages/local-store; npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
