name: Deploy Local Store
on:
  push:
    tags: 'release-local-store-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install yarn and lerna
        run: npm i -g yarn lerna

      - name: Run lerna bootstrap
        run: lerna bootstrap

      - name: Build monorepo
        run: lerna run build

      - name: Save npm token
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        working-directory: ./packages/local-store
        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish local-store to npm
        run: npm publish
        working-directory: ./packages/local-store
        
