name: Deploy Core SDK
on:
  push:
    tags: 'release-core-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install yarn and lerna
        run: npm i -g yarn lerna

      - name: Run lerna bootstrap
        run: lerna bootstrap

      - name: Build monorepo
        run: lerna run build

      - name: Build core-sdk docs
        run: lerna run build:docs

      - name: Save .env file
        run: echo "$ENV_FILE" > .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Setup AWS dir
        run: mkdir ~/.aws

      - name: Save AWS credentials
        run: echo "$AWS_CREDS" > ~/.aws/credentials
        env:
          AWS_CREDS: ${{ secrets.AWS_CREDS }}

      - name: Deploy core-sdk to S3
        run: lerna run deploy:core

      - name: Save npm token
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        working-directory: ./packages/core
        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish core-sdk to npm
        run: npm publish
        working-directory: ./packages/core
