name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install yarn and lerna
        run: npm i -g yarn lerna

      - name: Run lerna bootstrap
        run: lerna bootstrap

      - name: Build monorepo
        run: lerna run build
      
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install yarn and lerna
        run: npm i -g yarn lerna

      - name: Run lerna bootstrap
        run: lerna bootstrap
      
      - name: Build storybook
        run: lerna run build:storybook
